chain-specs/polimec-raw-chain-spec.json

Companion PR: https://github.com/Polimec/polimec-binaries/pull/1

chore: add helikon bootnodes

---

pallets/elections-phragmen/src/lib.rs

Add check on active stake lock in election phragmen pallet while voting. New balance stake should be at least similar to the active lock.
Currently someone can circumvent the active voting lock by first voting with a high balance (say 1000 PLMC) just before an election, and then set a new vote just after the election with a low balance (say 1 PLMC), thereby releasing the lock on the balance difference (999 PLMC). 
We check if there is a currently active lock. If the lock is in place, the balance required for voting has to be equal or higher then the currently active locked balance. 
I adjusted some failing tests to the new behaviour.

Fix voting issue in election pallet with premature unlock of tokens

---

nodes/parachain/src/chain_spec/testnet.rs
pallets/funding/src/benchmarking.rs
pallets/funding/src/functions.rs
pallets/funding/src/instantiator.rs
pallets/funding/src/lib.rs
pallets/funding/src/tests.rs
pallets/funding/src/types.rs

Reverts Polimec/polimec-node#187

Revert "Feature/plmc 463 refuse issuer on evaluate based on did"

---

pallets/funding/src/functions.rs
pallets/funding/src/lib.rs

Second try

---

runtimes/politest/src/lib.rs
runtimes/shared-configuration/src/funding.rs

:rocket: Politest upgrade

---

pallets/funding/src/instantiator/calculations.rs
pallets/funding/src/mock.rs
pallets/funding/src/tests/1_application.rs
pallets/funding/src/tests/2_evaluation.rs
pallets/funding/src/tests/3_auction.rs
pallets/funding/src/tests/4_community.rs
pallets/funding/src/tests/5_remainder.rs
pallets/funding/src/tests/misc.rs
pallets/funding/src/tests/mod.rs

Main info on #260 
- This PR focuses on fixing the application tests

✅  New decimal-aware price system - Part 2: Fix application tests

---

pallets/funding/src/tests/mod.rs

- This PR Fixes the evaluation tests

✅  New decimal-aware price system - Part 3: Fix evaluation tests

---

pallets/funding/src/tests/2_evaluation.rs

- Add a test to double check our new business logic on the evaluation round

 ⚗️ New decimal-aware price system - Part 4: Add evaluation test for different CT decimals

---

pallets/funding/src/instantiator/calculations.rs
pallets/funding/src/lib.rs
pallets/funding/src/tests/3_auction.rs

Main info on #260 
- This PR focuses on fixing the auction tests

✅  New decimal-aware price system - Part 6: Fix auction tests

---

Cargo.lock
integration-tests/penpal/Cargo.toml
integration-tests/src/constants.rs
integration-tests/src/tests/credentials.rs
integration-tests/src/tests/ct_migration.rs
integration-tests/src/tests/defaults.rs
integration-tests/src/tests/e2e.rs
integration-tests/src/tests/governance.rs
integration-tests/src/tests/vest.rs
nodes/parachain/src/chain_spec/politest.rs
pallets/funding/src/benchmarking.rs
pallets/funding/src/functions.rs
pallets/funding/src/tests/misc.rs
pallets/polimec-receiver/Cargo.toml
pallets/polimec-receiver/src/lib.rs
pallets/sandbox/src/mock.rs
polimec-common/test-utils/src/lib.rs
runtimes/politest/src/lib.rs
runtimes/shared-configuration/src/currency.rs
runtimes/shared-configuration/src/funding.rs

- This PR focuses on fixing the integration tests
- While fixing I noticed and fixed an issue where the CT migration logic was doing the funding check with a hardcoded value instead of the actual CT amount minted. (by funding check I refer to checking that the polimec sovereign account has enough tokens on the project chain).

✅ New decimal-aware price system - Part 10: Fix integration tests

---

polimec-common/test-utils/src/lib.rs
runtimes/shared-configuration/src/funding.rs

Increase the rounds duration to 1 hour, so @felixpolimec has enough time to test the various rounds.

🔧 Slow down the rounds in fast-mode

---

nodes/parachain/src/chain_spec/polimec.rs
nodes/parachain/src/chain_spec/politest.rs
pallets/funding/src/tests/3_auction.rs
runtimes/polimec/src/benchmarks/helpers.rs
runtimes/politest/src/benchmarks/helpers.rs

- Add a test for checking a wide range of decimals for CTs work as intended.
- We might have unexpected bugs when the decimals are too high or too low
- Similar to the evaluation test `different_decimals_ct_works_as_expected`

✅ New decimals auction test

---

pallets/funding/src/tests/4_community.rs
pallets/funding/src/tests/5_remainder.rs

- Add a test for checking a wide range of decimals for CTs work as intended.
- We might have unexpected bugs when the decimals are too high or too low
- Similar to the community test `different_decimals_ct_works_as_expected`

✅ New decimals remainder test

---

pallets/funding/src/tests/1_application.rs

- Add a check for the new min contribution ticket of 1USD
- We changed the logic down-stack
- add logic to `invalid_ticket_sizes` in the application test module

Add min contribution token logic to application test

---

pallets/funding/src/functions.rs
pallets/funding/src/lib.rs
pallets/funding/src/migration.rs
pallets/funding/src/settlement.rs
pallets/funding/src/tests/1_application.rs
pallets/funding/src/tests/2_evaluation.rs
pallets/funding/src/tests/3_auction.rs
pallets/funding/src/tests/4_community.rs
pallets/funding/src/tests/5_remainder.rs
pallets/funding/src/tests/8_ct_migration.rs
pallets/funding/src/types.rs
runtimes/politest/src/lib.rs

- Replace all calls to the nested errors to the new un-nested ones

🎨 Fix error uses

---

nodes/parachain/Cargo.toml
runtimes/polimec/Cargo.toml
runtimes/polimec/src/lib.rs
runtimes/shared-configuration/src/funding.rs

Set the `VerifierPublicKey` to a public key matching the private key used to generate the JWT in production.

feat: set the production verifier public key

---

Cargo.lock
Cargo.toml
nodes/parachain/src/service.rs

Bump the workspace version to `0.7.0`

🔖 Release Polimec 0.7.0

---

pallets/funding/src/lib.rs

Misc error content changes; Leo/Ken

Update lib.rs (Misc error content changes; Leo/Ken)

---

pallets/funding/src/tests/2_evaluation.rs

- Test what happens when you evaluate with frozen balance, i.e. a hold on a freeze.
- To double-check our assumptions about these interactions
- An evaluator holds ED + an amount frozen.
- It uses that frozen amount to evaluate
- The project fails
- He get's slashed
- The treasury receives the slashed amount as free balance
- The evaluator ends up with less free balance than the original freeze restriction (intended)
`can_evaluate_with_frozen_tokens` inside `2_evaluation.rs`
Next PRs will do the same for other participation types

✅ Test freeze restrictions on evaluations

---

runtimes/shared-configuration/src/funding.rs

Change the Auction Duration to 4 + 1 days (src: https://hub.polimec.org/learn/funding-process/funding-round#auction-round)

leo: fix the auction duration

---

pallets/funding/src/functions/4_contribution.rs
pallets/funding/src/lib.rs
pallets/funding/src/types.rs

- Add `when` to `ContributionInfo`
So the UI can easily know when the contribution was made and display it
add the field to the type, and assign it to `now` inside `do_contribute`
Run normal tests, since this new field shouldn't affect the logic

✨ Add `when` to `ContributionInfo`

---

runtimes/shared-configuration/src/funding.rs

Simplify the `#[cfg(...)]`  as reported in https://github.com/Polimec/polimec-node/pull/342#discussion_r1660659217.

chore: cleanup cfg

---

integration-tests/src/constants.rs
integration-tests/src/tests/vest.rs
nodes/parachain/src/chain_spec/common.rs
pallets/funding/src/benchmarking.rs
pallets/funding/src/functions/6_settlement.rs
pallets/funding/src/lib.rs
pallets/funding/src/mock.rs
pallets/funding/src/tests/2_evaluation.rs
pallets/linear-release/src/tests.rs
pallets/parachain-staking/src/mock.rs
pallets/parachain-staking/src/tests.rs
runtimes/polimec/src/custom_migrations/deposit_dust.rs
runtimes/polimec/src/lib.rs
runtimes/shared-configuration/src/fee.rs

Send the slashed PLMC to the correct treasury according the [Knowledge Hub](https://hub.polimec.org/learn/on-chain-treasury).

🩹 Send the slashed PLMC to the Blockchain Operation Treasury 

---

Cargo.lock
integration-tests/Cargo.toml
nodes/parachain/Cargo.toml
pallets/funding/Cargo.toml
pallets/funding/src/functions/1_application.rs
pallets/funding/src/functions/2_evaluation.rs
pallets/funding/src/functions/3_auction.rs
pallets/funding/src/functions/5_funding_end.rs
pallets/funding/src/functions/6_settlement.rs
pallets/funding/src/functions/misc.rs
pallets/funding/src/instantiator/mod.rs
pallets/funding/src/lib.rs
pallets/funding/src/mock.rs
pallets/polimec-receiver/Cargo.toml
pallets/sandbox/src/mock.rs
runtimes/polimec/Cargo.toml
runtimes/polimec/src/lib.rs

Chores' PR to fix various problems identified by `clippy` and `zepter`. It also removes the unused `futures` dependency from pallet-funding and the now unused `PreImageLimit` config type.

♻️ Summer cleanup

---

pallets/funding/src/functions/2_evaluation.rs
pallets/funding/src/functions/3_auction.rs
pallets/funding/src/functions/4_contribution.rs
pallets/funding/src/functions/5_funding_end.rs
pallets/funding/src/functions/6_settlement.rs
pallets/funding/src/functions/misc.rs
pallets/funding/src/instantiator/chain_interactions.rs
pallets/funding/src/lib.rs
pallets/funding/src/runtime_api.rs
pallets/funding/src/tests/misc.rs
pallets/funding/src/tests/runtime_api.rs
pallets/funding/src/types.rs
runtimes/polimec/src/benchmarks/mod.rs

🧹 Cargo fmt

---

pallets/funding/src/lib.rs

- Initial fixing of stale documentation on pallet-funding

✍🏻 Fix docs

---

pallets/funding/src/benchmarking.rs
pallets/funding/src/functions/6_settlement.rs
pallets/funding/src/instantiator/calculations.rs
pallets/funding/src/instantiator/chain_interactions.rs
pallets/funding/src/lib.rs
pallets/funding/src/mock.rs
pallets/funding/src/runtime_api.rs
pallets/funding/src/tests/6_settlement.rs
pallets/funding/src/tests/runtime_api.rs
runtimes/polimec/src/lib.rs

- Make multiplier 1 not have a vesting schedule of 1
- Add runtime API for our UI to check which schedules can be merged based on a delta of their end dates
- Because schedules are limited

✨ Vesting schedule merge runtime API

---

justfile
pallets/funding/src/lib.rs
scripts/zombienet/polimec-paseo-local.toml

Fix zombienet config and a small warning while compiling with the `on-chain-release-build` feature flag.

🩹 Update zombienet config

---

Cargo.lock
Cargo.toml
pallets/dispenser/src/extensions.rs
pallets/funding/Cargo.toml
pallets/funding/src/lib.rs
pallets/funding/src/mock.rs
runtimes/polimec/Cargo.toml
runtimes/polimec/src/lib.rs

Remove the `Random` pallet, since there is not anymore a Candle Phase in the Auction Round. 
I added also the `RemovePallet` migration, and removed the old ones.

⚰️ Remove Randomness pallet (PLMC-602)

---

Cargo.lock
pallets/funding/src/functions/1_application.rs
pallets/funding/src/functions/2_evaluation.rs
pallets/funding/src/functions/3_auction.rs
pallets/funding/src/functions/4_contribution.rs
pallets/funding/src/functions/5_funding_end.rs
pallets/funding/src/lib.rs
pallets/funding/src/mock.rs
pallets/funding/src/tests/1_application.rs
pallets/funding/src/tests/runtime_api.rs
polimec-common/common/Cargo.toml
polimec-common/common/src/lib.rs
polimec-common/test-utils/Cargo.toml
polimec-common/test-utils/src/lib.rs
runtimes/polimec/Cargo.toml
runtimes/polimec/src/xcm_config.rs

- Minor changes like safe math and documentation, following the review made by BlockDeep.
- Mainly deleted some stale doc comments. For now most functions in the functions folder have no doc comments. We might add new ones if we feel like it.

🤓 Blockdeep Review Changes

---

polimec-common/common/src/credentials/mod.rs
polimec-common/test-utils/src/lib.rs

Increase credential bounded vec size
