- README.md
- scripts/zombienet/native/local-testnet.toml
In the README the guide to starting a node locally had not been updated. This PR fixes the README and adds a new Zombienet `.toml` to start a testnet locally.
> Improve README

- runtimes/shared-configuration/src/currency.rs
Increase PLMC ED by 10x
Not sure, @lrazovic could comment on that
Change the const in the shared-configuration
Run all tests and check they didn't break
> Increase ED by 10x. 0.001 PLMC -> 0.01 PLMC

- Cargo.lock
- Cargo.toml
- runtimes/base/src/lib.rs
Bump the version to `0.5`.
We are ready for a new runtime upgrtade! A tentative changelog is available here: https://github.com/Polimec/polimec-node/releases/tag/v0.5.0
> chore: prepare 0.5 release

- pallets/funding/src/functions.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/types.rs
Try to simplify ticket sizes by decreasing amount of trait bounds, structs and traits:
- Split the rounds into two seperate items in the metadata.
- Delete all the specific traits and simplify it to TicketSizeValidityCheck and TicketSizeParticipationChecks
- Other changes
TODO:
- Switch from Vec<InvestorTypeUSDBounds> to BoundedVec. 
- Fix tests, benchmarks, etc (did not try them) 
- Potentially still to complicated as we currently only check in the full is_valid flow if bids for both Prof and Inst are > 5k. - - Could remove all these traits and more and do a simple check in the is_valid from ProjectMetadata where we check if bidding Ticket both have a lower bound > 5k.
- min_price is now not used in the validity checks. Probably needed for check based on min CT instead of USD, so I let …
> potential changes

- Cargo.lock
- Cargo.toml
- runtimes/base/Cargo.toml
- runtimes/base/src/custom_migrations.rs
- runtimes/base/src/custom_migrations/deposit_dust.rs
- runtimes/base/src/custom_migrations/init_pallet.rs
- runtimes/base/src/custom_migrations/mod.rs
- runtimes/base/src/custom_migrations/unhashed_migration.rs
- runtimes/base/src/lib.rs
- runtimes/testnet/Cargo.toml
- `DepositDust`: After the fix on the dust (https://github.com/Polimec/polimec-node/pull/193) we have to deposit the dust wrongly burned to the Blockchain Operation Treasury.
- `UnhashedMigration`: At the TGE one account received a wrong `VestingInfo`, we need to adress this. 
- Build the runtime with the `try-runtime` feature: `cargo b -r -p polimec-base-runtime --features try-runtime`
- Execute the Try Runtime CLI:
```
try-runtime \
--runtime target/release/wbuild/polimec-base-runtime/polimec_base_runtime.compact.compressed.wasm \
on-runtime-upgrade \
live --uri wss://rpc.polimec.org:443
```
> Migration: Issuance and Dust fix

- runtimes/polimec/src/lib.rs
- runtimes/politest/src/lib.rs
Few pallets were missing in the `define_benchmarks!` macro.
> chore: add missing pallets in define_benchmarks!

- Cargo.lock
- integration-tests/src/tests/credentials.rs
- nodes/parachain/Cargo.toml
- pallets/dispenser/Cargo.toml
- pallets/funding/Cargo.toml
- pallets/oracle-ocw/Cargo.toml
- runtimes/politest/src/lib.rs
Deploy the latest updates on Politest. 
```
try-runtime \
--runtime target/release/wbuild/politest-runtime/politest_runtime.compact.compressed.wasm \
on-runtime-upgrade  \
live --uri wss://beta.rolimec.org:443
```
```
[2024-04-12T14:52:06Z INFO  remote-ext] replacing wss:// in uri with https://: "https://beta.rolimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-04-12T14:52:07Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0xaefdd861091fee97ac4bacdbf63b7edcada5143559f15fc2853aa066ec6a1e7e
[2024-04-12T14:52:07Z INFO  remote-ext] since no prefix is filtered, the data for all pallets will be downloaded
[2024-04-12T14:52:07Z INFO  remote-ext] scraping key-pairs from …
```
> 🚀 Upgrade politest

- runtimes/shared-configuration/src/funding.rs
- Reduce all fast-mode funding timings to 10 minutes
Testing round transitions manually on Politest takes forever currently
> Reduce fast-mode times to 10min

- justfile
- nodes/parachain/src/chain_spec/politest.rs
- pallets/funding/src/benchmarking.rs
- pallets/linear-release/src/benchmarking.rs
- runtimes/politest/src/lib.rs
- fix all benchmarks that errored out when running `just dry-run-benchmarks`
- Pallet funding required funding the ct treasury account with ed on the chain spec
- Linear release required using config types in the benchmark code instead of hardcoded values
- Run `just dry-run-benchmarks` and see if no errors pops up
> 🐛 Fix benchmarks

- runtimes/polimec/src/lib.rs
- Set the `DmpQueue` version to latest (2).
- Remove migrations already released. 
- Bump the `spec-version`, so we can use the `try-runtime-cli` to test the new runtimes.
- The `try-runtime-cli` was not working properly in the last upgrade, so we missed this. https://github.com/Polimec/polimec-node/pull/240
```
[2024-04-19T14:33:35Z INFO  remote-ext] replacing wss:// in uri with https://: "https://rpc.polimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-04-19T14:33:36Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0x332a6845b06275a10e53d99d3bc0e9e25f041cea283f2d613af3ca94c46c4e97
[2024-04-19T14:33:36Z INFO  remote-ext] since no prefix is filtered, the data for all …
```
> 🏗️ Release migrations

- Cargo.lock
- runtimes/politest/src/lib.rs
Check title.
For some reason cargo lock was updated too
try-runtime cli:
srtool output:
```
✨ Your Substrate WASM Runtime is ready! ✨
✨ WASM  : runtimes/politest/target/srtool/production/wbuild/politest-runtime/politest_runtime.compact.wasm
✨ Z_WASM: runtimes/politest/target/srtool/production/wbuild/politest-runtime/politest_runtime.compact.compressed.wasm
Summary generated with srtool v0.15.0 using the docker image paritytech/srtool:1.77.0:
Package     : politest-runtime v0.6.0
GIT commit  : 66910d4190014f8b4ac600fde9b046d160727e59
GIT tag     : v0.6.0
GIT branch  : 04-22-bump_politest_runtime_to_v0.7
Rustc       : rustc 1.77.0 (aedd173a2 2024-03-17)
Time        : 2024-04-22T14:36:14Z
== Compact
Version          : politest-7000 (politest-0.tx2.au1)
Metadata         : V14
Size …
```
>  🔖  Release Politest v0.7.0

- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/weights.rs
- runtimes/polimec/src/lib.rs
- Fix evaluation logic and benchmarks
- Add a test for this new logic
- We changed the evaluation code and forgot to adapt some dependent code paths
- Evaluation benchmarks go from 2 -> 1. Since we removed in another PR the automatic unbending.
- Add a check for the MaxEvaluationPerUser cap
- A new test called `cannot_evaluate_more_than_user_limit`
> 🩹 fix evaluation logic and benchmarks

- runtimes/politest/src/lib.rs
- runtimes/shared-configuration/src/funding.rs
This also includes evaluation fix.
```sh
polimec-node on  04-23-politest_v0.7.1_reduce_evaluation_auction_durations_by_50_ via 🦀 v1.76.0-nightly took 1m27s 
❯ try-runtime --runtime ./target/release/wbuild/politest-runtime/politest_runtime.compact.compressed.wasm on-runtime-upgrade live --uri wss://beta.rolimec.org:443
[2024-04-23T11:28:04Z INFO  remote-ext] replacing wss:// in uri with https://: "https://beta.rolimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-04-23T11:28:04Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0x6dfb43932d7944c22efe00a72274baa803a14e6e36b774b76872b3a99d2a7fcf
[2024-04-23T11:28:04Z INFO  remote-ext] since no prefix is filtered, the data …
```
> Politest v0.7.1: reduce evaluation+auction durations by 50%

- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- pallets/funding/src/tests/mod.rs
- runtimes/polimec/src/lib.rs
Restructure remainder round tests into modules
Better clarity
Follow the same structure as previous modules
> 🧑‍💻 Restructure remainder tests

- nodes/parachain/src/service.rs
Enable HTTP requests from offchain workers.
When we merged https://github.com/Polimec/polimec-node/commit/0f4573ca66b73cd9ee1750463dfcf2909d7a70d8 we accidentally forbid the HTTP requests from the offchain workers. This feature is needed since otherwise the selected nodes cannot fetch and submit the prices.
> feat: enable http requests

- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- Add test that we cannot use evaluation bond of project x for project y
- One test in each bids,community, and remainder modules
> ✅ test evaluation bond cannot be used on another project participation

- pallets/funding/src/functions.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
This PR focuses on fixing the community tests
> ✅  New decimal-aware price system - Part 7: Fix Community tests

- pallets/funding/src/tests/misc.rs
This PR focuses on fixing the misc and async tests
> ✅  New decimal-aware price system - Part 9: Fix Misc & Async tests

- pallets/funding/src/functions.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/types.rs
This pull request includes Decentralized Identifier (DID) in Evaluation (`EvaluationInfo`) and Contribution (`ContributionInfo`) structs.
> ✨ Store the DID used in Evaluation or Contribution

- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/tests/4_community.rs
- Add a test for checking a wide range of decimals for CTs work as intended.
- We might have unexpected bugs when the decimals are too high or too low
- Similar to the auction test `different_decimals_ct_works_as_expected`
> ✅ New decimals community test

- pallets/funding/src/tests/1_application.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/types.rs
- The decimals in the token information can now only be a number from 4 to 20 inclusive.
- Too low numbers means a very big whole part in the Fixedu128, too high means a very big decimal part in the same type.
- We want to make sure the price is representable
- add a new check on the metadata validation function
`unaccepted_ct_decimals` on the application test file
- We need to also check that the allocation size is big enough to represent the decimals specified by the user. In another PR though
> ✨ Accept only CT decimals from 4 to 20

- pallets/funding/src/tests/1_application.rs
- pallets/funding/src/types.rs
- Reject project metadatas on creation and edit where the allocation size is smaller than the specified decimals.
- It introduces memory leaks, which would behave the same as panics and stall our chain
- add a new check on the metadata validation function
`allocation_smaller_than_decimals` on application test file
> ⚡️ Add check for allocation smaller than decimals

- Cargo.lock
- integration-tests/src/tests/basic_comms.rs
- integration-tests/src/tests/defaults.rs
- integration-tests/src/tests/e2e.rs
- integration-tests/src/tests/governance.rs
- integration-tests/src/tests/vest.rs
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/1_application.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/tests/mod.rs
- pallets/funding/src/traits.rs
- pallets/funding/src/types.rs
- polimec-common/common/src/lib.rs
- runtimes/polimec/src/lib.rs
- runtimes/politest/src/lib.rs
- runtimes/shared-configuration/Cargo.toml
- runtimes/shared-configuration/src/currency.rs
- runtimes/shared-configuration/src/funding.rs
- Find ways to avoid unrepresentability of issuer-set tokenomics on our own types
- We let issuers choose whatever price, allocation, and decimals they want, but we still need to convert those into our own FixedU128 price, and 6 decimal USD amounts. 
- This could potentially lead to some issuer-set tokenomics being unrepresentable with our own types, For example due to their CT being too high in value, and we couldn't represent 1 US cent with their lowest possible CT amount, or their price decimals having more decimals than our Price type, and it saturating to 0.
- Limit the decimals to 6-18 range, and price to 0.00001-1000
- After experimenting some on the misc tests, I came to the conclusion that the best course now is to severely restrict the decimals and price that the issuer can put. …
> Make sure USD is representable with CT decimal/price combo

- scripts/chopsticks/assethub-transfers/polkadot-assethub.yml
- scripts/chopsticks/assethub-transfers/polkadot-polimec.yml
- Add chopstick config files to test asset hub transfers to Polimec
- To make sure our live Polimec xcm config is correct
- add balances to the sovereign account and sender in assethub, and create the assets for DOT, USDC, and USDT on Polimec
USDT transfer encoded call to execute on AssetHub:
```
0x1f020101010041340100010100ba143e2096e073cb9cddc78e6f4969d8a02160d716a69e08214caf5339d88c420104000002043205011f000284d71700000000
```
> Try out AssetHub transfers with chopsticks

- pallets/funding/src/types.rs
- Make lower ticket bounds non-optional
- Add min low bound of 1USD for contributions
- The 1USD bound was discussed and agreed with Luca
- Since both tickets now have a required lower bound, makes no sense to keep it optional since it will never be accepted when None
- Remove all references to Option on the lower bound, and add a check for 1USD on the ticket size in project metadata validation
In a future PR
Fixes of all the other tests in the next PR
> Remove optional mins on ticket sizes

- pallets/funding/src/migration.rs
- runtimes/politest/src/lib.rs
- scripts/chopsticks/standalone/rococo-politest.yml
- Bump Politest one minor version
- Add migration to v2 for pallet funding
try-runtime output:
```sh
polimec-node on  05-06-bump_politest_version [!] via 🦀 v1.76.0-nightly took 7m50s 
❯ try-runtime --runtime ./target/release/wbuild/politest-runtime/politest_runtime.compact.compressed.wasm on-runtime-upgrade live --uri wss://beta.rolimec.org:443
[2024-05-07T08:05:38Z INFO  remote-ext] replacing wss:// in uri with https://: "https://beta.rolimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-05-07T08:05:38Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0xdd9c9b3ab95fdaca010e4d3819b5b4493175b2cbbf1c4bfaf7d0022a4b6be5e9
[2024-05-07T08:05:38Z INFO  remote-ext] since no …
```
> bump politest version

- runtimes/polimec/src/lib.rs
This PR adds the start_evaluation and evaluate extrinsics to the list of allowed funding extrinsics. 
And bumps spec_version to 0.7.1.
> :sparkles: Runtime release 0.7.1

- Cargo.lock
- justfile
- nodes/parachain/Cargo.toml
- nodes/parachain/src/command.rs
- nodes/parachain/src/service.rs
- pallets/polimec-receiver/Cargo.toml
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/lib.rs
- runtimes/politest/Cargo.toml
- runtimes/politest/src/lib.rs
- runtimes/shared-configuration/Cargo.toml
- scripts/zombienet/native/local-testnet.toml
Promote the code behind the `async-backing` feature to production. More context [in the wiki](https://wiki.polkadot.network/docs/maintain-guides-async-backing). 
After async-backing was enabled on Polkadot ([Referendum 688](https://polkadot.polkassembly.io/referenda/688)), collators began reporting a few instances of panics while collating:
```
polimec-node[739]: ====================
polimec-node[739]: Version: 0.6.0-ced567ba1bb
polimec-node[739]:    0: sp_panic_handler::set::{{closure}}
polimec-node[739]:    1: std::panicking::rust_panic_with_hook
polimec-node[739]:    2: std::panicking::begin_panic_handler::{{closure}}
polimec-node[739]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
polimec-node[739]:    4: rust_begin_unwind
polimec-node[739]:    5: …
```
> 🐛 Promote async-backing feature to production

- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/settlement.rs
- pallets/funding/src/tests/7_settlement.rs
- Change account for the payout of funding assets to funding destination account instead of issuer account.
- We weren't using the funding destination account as intended
- on the settle successful bid and successful contribution functions, change the payout account
- Added a new instantiator function `assert_total_funding_paid_out` which is now used on the settlement test `can_settle_accepted_project`
> 🐛 Payout funding assets to destination account

- justfile
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/lib.rs
- Fix Polimec benchmarks
- Use the testing verifier key when running benchmarks and tests 
- `just dry-run-benchmarks polimec`
> 🐛 Fix polimec benches

- justfile
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions.rs
- pallets/funding/src/instantiator/async_features.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/6_funding_end.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/tests/mod.rs
- Fix instant-mode benchmarks
- Improve dry-run-benches just command
- Improve phase transition points
- The calculation on the instantiator was inaccurate because the phase transition points were 1 block off
- Just command can now run for a specific mode and runtime
- Now the start block of a state is the same block where on_initialize is called. Before it was the next block, even though the current one was still possible to call the extrinsics for that state
`just dry-run-benchmarks instant-mode`
>  ⚡️ Improve phase transition points and fix instant-mode 

- pallets/funding/src/instantiator/async_features.rs
- pallets/funding/src/tests/5_remainder.rs
- Add and modify tests to remainder round
- We were missing some if we compare it to the community tests. They should be mostly the same
- Comparing one file to the other and adding the ones that we were missing
- Run the whole remainder round test file
- We might be missing some logical paths, please check if you can come up with anything else
- Also fixed a bug in the async instantiator where creating a finished project was not waiting until the block advanced to the finished transition
> ✅ Comprehensive remainder round tests

- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/1_application.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/functions/4_contribution.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/instantiator/async_features.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/types.rs
- Spread out the WAP on_initialize calculation into 2 blocks
- Because the ref time was too close to the block limit
- Create a do_end_auction_closing function that does the deciding of which bids are successful, and refunds/deletes failed ones
- do_start_community now does the WAP calculation only
- Run normal tests, all logic should be maintained
> ✨ Optimize wap calculation

- chain-specs/polimec-raw-chain-spec.json
Add Amforc Bootnode
More resilience
via Infrastructure
```
./polimec-node --chain polimec --base-path /tmp/node --reserved-only --reserved-nodes "/dns/polimec.bootnode.amforc.com/tcp/29999/wss/p2p/12D3KooWSNA6RHfNC9XPCoftFDsuXM2JkVHJEejHWSe3X8Jf9v9Y" --no-hardware-benchmarks
```
```
./polimec-node --chain polimec --base-path /tmp/node --reserved-only --reserved-nodes "/dns/polimec.bootnode.amforc.com/tcp/30016/p2p/12D3KooWSNA6RHfNC9XPCoftFDsuXM2JkVHJEejHWSe3X8Jf9v9Y" --no-hardware-benchmarks
```
No
> add amforc bootnode

- pallets/dispenser/src/benchmarking.rs
- pallets/dispenser/src/lib.rs
- pallets/dispenser/src/mock.rs
- pallets/dispenser/src/tests.rs
- polimec-common/test-utils/src/lib.rs
- runtimes/polimec/src/lib.rs
- runtimes/politest/src/lib.rs
- runtimes/shared-configuration/src/assets.rs
Add a policy check to the dispenser pallet
We need to filter user credentials based on a specified policy. Policy can be found at https://cloudflare-ipfs.com/ipfs/QmVdGSxuWcamYEmYJjR3gvZucqQpp4Jnf6tqJABHwKZVo3
Added a Pallet config item for the whitelisted policy. 
Added `user_cannot_dispense_with_wrong_policy` and updated the rest of the tests.
> :sparkles: add policy check to dispenser pallet

- pallets/funding/src/storage_migrations.rs
- runtimes/polimec/src/lib.rs
- runtimes/politest/src/lib.rs
- New runtime for Politest and Polimec
- WAP calculation changed
- Evaluator rewards fixed
- Bump version and write migration for ProjectDetails
Try-runtime output for polimec:
```sh
polimec-node on  06-03-new-release [!] via 🦀 v1.76.0-nightly 
❯ try-runtime --runtime ./target/release/wbuild/polimec-runtime/polimec_runtime.compact.compressed.wasm on-runtime-upgrade live --uri wss://rpc.polimec.org:443
[2024-06-03T15:07:18Z INFO  remote-ext] replacing wss:// in uri with https://: "https://rpc.polimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-06-03T15:07:18Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0xd014d5b26ca93fab61eb751f501e7c3dd8261294312177d192863dbe09b4 …
```
> ⬆️ 0.7.5 Release Polimec/Politest

- pallets/funding/src/storage_migrations.rs
- scripts/chopsticks/polimec-testing/polkadot-polimec.yml
- scripts/zombienet/native/polkadot-polimec.toml
- Fix a bug in the storage migration of pallet funding from 2->3
- ProjectStatus was wrongly migrated inside ProjectDetails
- We added a new status `CalculatingWap` which changed the indices of all enums when encoded, which we forgot to account for
Tested by forking Polkadot and Polimec with chopsticks using `npx @acala-network/chopsticks@latest xcm -r polkadot -p scripts/chopsticks/polimec-testing/polkadot-polimec.yml
`
The new chopsticks script replaces the Council and TC with test accounts, which means we can quickly do sudo operations
> 🔧 Fix storage migration

- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/tests/6_funding_end.rs
- pallets/funding/src/tests/7_settlement.rs
- Test more logic branches of the code
- Check https://linear.app/polimec/issue/PLMC-544/settlement
> ✅ Comprehensive settlement tests

- pallets/funding/src/mock.rs
- pallets/funding/src/tests/3_auction.rs
- Test what happens when you bid with frozen balance, i.e. a hold on a freeze.
- To double-check our assumptions about these interactions
- An bidder holds ED + an amount frozen.
- It uses that frozen amount to bid
- The project fails / succeeds
- If it fails, he gets the PLMC back, if it succeeds, he waits and then vests the full amount.
- In the end, the user still has the freeze restriction
`can_bid_with_frozen_tokens_funding_success` and  `can_bid_with_frozen_tokens_funding_failed`
Next PRs will do the same for other participation types
> ✅ Test freeze restrictions on bids

- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- runtimes/politest/src/lib.rs
- Test what happens when you contribute (community/remainder) with frozen balance, i.e. a hold on a freeze.
- To double-check our assumptions about these interactions
- An contributor holds ED + an amount frozen.
- It uses that frozen amount to contribute
- The project fails / succeeds
- If it fails, he gets the PLMC back, if it succeeds, he waits and then vests the full amount.
- In the end, the user still has the freeze restriction
`can_contribute_with_frozen_tokens_funding_success` and  `can_contribute_with_frozen_tokens_funding_failed`
> ✅ Test freeze restrictions on contributions

- pallets/funding/src/benchmarking.rs
- pallets/funding/src/instantiator/async_features.rs
- pallets/funding/src/instantiator/calculations.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- pallets/funding/src/tests/7_settlement.rs
- pallets/funding/src/tests/misc.rs
- Make it possible to add the ED amount to PLMC calculations on evaluations/auctions/contributions
- To avoid having to calculate and mint the ED separately
- Add a new bool `with_ed` to the functions
Existing tests should pass, now that a lot of them were updated
> 🧑‍💻 Optional ED inclusion on inst PLMC calculations

- integration-tests/src/tests/credentials.rs
- Fix dispenser test in integration-tests
- Add CID to the jwt
> 🔧 Fix dispenser test

- runtimes/politest/src/lib.rs
- runtimes/shared-configuration/src/funding.rs
- runtimes/shared-configuration/src/lib.rs
- New Politest release with faster rounds
- So Simon can test faster
Did a try-runtime check and it was fine. Built with srtool
> ⬆️ Faster fast-mode for politest

- integration-tests/src/constants.rs
- integration-tests/src/tests/credentials.rs
- integration-tests/src/tests/governance.rs
- integration-tests/src/tests/mod.rs
- integration-tests/src/tests/xcm_config.rs
- runtimes/polimec/src/xcm_config.rs
- When buying execution with the XCM instruction`BuyExecution`, make the amount spent go to the treasury instead of being burnt
💸
- Modify the traders assigned to `XcmConfig::Trader`
- Put another custom generic inside `FixedRateOfFungible` and `UsingComponents` which sends to treasury instead of burning
In integration tests, `xcm_config::execution_fees_go_to_treasury`
> 🔧 Change XCM execution fee destination to treasury

- integration-tests/src/constants.rs
- integration-tests/src/tests/credentials.rs
- integration-tests/src/tests/governance.rs
- integration-tests/src/tests/mod.rs
- integration-tests/src/tests/xcm_config.rs
- runtimes/polimec/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
Upgrade Polimec
Whitelist the auction and root calls
Add them to the `Basecall` filter
try-runtime output:
```
❯ try-runtime --runtime ./target/release/wbuild/polimec-runtime/polimec_runtime.compact.compressed.wasm on-runtime-upgrade live --uri wss://rpc.polimec.org:443
[2024-06-14T13:30:20Z INFO  remote-ext] replacing wss:// in uri with https://: "https://rpc.polimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-06-14T13:30:20Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0xdd9f49b5e3403d646002a5329323dbb0e69ff3e29068277338bcc4322d016eca
[2024-06-14T13:30:20Z INFO  remote-ext] since no prefix is filtered, the data for all pallets will be downloaded …
```
> 🔖 Whitelist pallet_funding sudo and root calls. New Polimec Release

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/constants.rs
- integration-tests/src/lib.rs
- integration-tests/src/tests/credentials.rs
- integration-tests/src/tests/ct_migration.rs
- integration-tests/src/tests/defaults.rs
- integration-tests/src/tests/e2e.rs
- integration-tests/src/tests/governance.rs
- integration-tests/src/tests/oracle.rs
- integration-tests/src/tests/reserve_backed_transfers.rs
- integration-tests/src/tests/vest.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/lib.rs
- runtimes/politest/src/lib.rs
- runtimes/shared-configuration/Cargo.toml
- runtimes/shared-configuration/src/identity.rs
- Remove politest from integration tests, and replace all references with polimec
- First step in deleting politest
`cargo test --package integration-tests`
> Remove politest from integration-tests

- integration-tests/penpal/src/lib.rs
- pallets/funding/src/functions/7_ct_migration.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/types.rs
- runtimes/polimec/src/lib.rs
- runtimes/politest/src/lib.rs
- Allow parachains to have their polimec receiver pallet assigned to any pallet index
- We should not opinionate that
- We no longer have the config item `PolimecReceiverInfo`. 
- We previously needed it because the `PalletInfo` items returned on the pallet query were set to private. Now we can just check the pallet name and save the index for later
- Modify penpal so the receiver has a different index and run the integration ct_migration tests
> 👨🏻‍💻 Allow polimec receiver pallet to have any index

- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/2_evaluation.rs
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- pallets/funding/src/tests/6_funding_end.rs
- pallets/funding/src/tests/7_settlement.rs
- pallets/funding/src/tests/mod.rs
- pallets/funding/src/weights.rs
- runtimes/polimec/src/weights/pallet_funding.rs
- Schedule the start of settlement for a failed evaluation round
- Settlement functions now check that the settlement was started, and the round is correct (with new more descriptive errors)
- We forgor 💀
Refactored some tests to adapt to the new logic
We need to re-benchmark end_evaluation_failure since it has a new parameter. For now the parameter is added but not used
> 🐛 Start failed evaluation settlement

- pallets/funding/src/lib.rs
This pr adds the `root_do_end_auction_closing` extrinsic and uses this extrinsics weight as fallback in on_initialize for the do_end_auction_closing, that is currently set incorrectly
> fix wrong fallback weight in on_initialize

- runtimes/polimec/src/benchmarks/mod.rs
- runtimes/polimec/src/lib.rs
- Add community round - pre settlement calls to the basecall filter.
- Fix a benchmark test and runtime test build.
To enable calls for next rounds
> add next round calls to filter + some small feature flag fixes

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/penpal/Cargo.toml
- integration-tests/penpal/build.rs
- integration-tests/penpal/src/lib.rs
- integration-tests/penpal/src/weights/block_weights.rs
- integration-tests/penpal/src/weights/extrinsic_weights.rs
- integration-tests/penpal/src/weights/mod.rs
- integration-tests/penpal/src/weights/paritydb_weights.rs
- integration-tests/penpal/src/weights/rocksdb_weights.rs
- integration-tests/penpal/src/xcm_config.rs
- pallets/polimec-receiver/Cargo.toml
- pallets/polimec-receiver/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
- Update penpal runtime
- To make sure our CT migration works with the latest xcm conventions
- Replace the old xcm with the new xcm from sdk 1.6.
- Add the polimec receiver and vesting pallets
- Modify the xcm config
`cargo test -p integration-tests`
> ⬆️ Update penpal

- runtimes/polimec/src/xcm_config.rs
- Make messages with a trailing `SetTopic` pass the barriers
- This is a convention used by parachains. Any query we send will be responded with the response + topic, and currently our barriers don't expect that
- The wrapper checks if at the end there is a `SetTopic`, and if so removes it and sets the topic of the executor
No tests
Discussion on the SDK repo:
https://github.com/paritytech/polkadot-sdk/issues/4868
> 🔧 Accept trailing topics on xcm barrier

- runtimes/polimec/src/lib.rs
*Srtool Output:*
```sh
✨ Your Substrate WASM Runtime is ready! ✨
✨ WASM  : runtimes/polimec/target/srtool/production/wbuild/polimec-runtime/polimec_runtime.compact.wasm
✨ Z_WASM: runtimes/polimec/target/srtool/production/wbuild/polimec-runtime/polimec_runtime.compact.compressed.wasm
Summary generated with srtool v0.15.0 using the docker image paritytech/srtool:1.77.0:
Package     : polimec-runtime v0.7.0
GIT commit  : 6ccd7ce1aaf1bd3a0c5d36e19a5d28a4e92b209a
GIT tag     : v0.7.3
GIT branch  : 06-24-new_polimec_release
Rustc       : rustc 1.77.0 (aedd173a2 2024-03-17)
Time        : 2024-06-24T14:49:01Z
== Compact
Version          : polimec-mainnet-7004 (polimec-mainnet-0.tx2.au1)
Metadata         : V14
Size             : 5.06 MB (5303976 bytes)
setCode          : …
```
> 🔖 Polimec release v0.7.4

- runtimes/polimec/src/lib.rs
Try-runtime output:
```
❯ try-runtime --runtime ./target/release/wbuild/polimec-runtime/polimec_runtime.compact.compressed.wasm on-runtime-upgrade live --uri wss://rpc.polimec.org:443
[2024-06-24T15:12:08Z INFO  remote-ext] replacing wss:// in uri with https://: "https://rpc.polimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-06-24T15:12:09Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0x3030b10ffda583e4429d864d6f05e000bb58bbb5959c8c828eeb98056377d1fb
[2024-06-24T15:12:09Z INFO  remote-ext] since no prefix is filtered, the data for all pallets will be downloaded
[2024-06-24T15:12:09Z INFO  remote-ext] scraping key-pairs from remote at block height …
```
> Fix transaction version v0.7.4

- runtimes/polimec/src/lib.rs
- runtimes/shared-configuration/src/funding.rs
- Whitelist settlement calls
- Reduce `SuccessToSettlementTime` from 4 days to 1 hour
- Apillon is close to funding end
- We don't need the long settlement time as of now, so better UX to make it short.
try-runtime check
```
❯ try-runtime --runtime ./target/release/wbuild/polimec-runtime/polimec_runtime.compact.compressed.wasm on-runtime-upgrade live --uri wss://rpc.polimec.org:443
[2024-07-01T07:52:40Z INFO  remote-ext] replacing wss:// in uri with https://: "https://rpc.polimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-07-01T07:52:41Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0x85720c8380e26e02746101835cecd8d7d62f64705d4b854f7bb9ff7bb8af753a …
```
> 🔖 Release 0.7.5

- pallets/funding/src/lib.rs
- We forgot to add the benchmarked weights to some extrinsics like settlements
> 💀 Add real weights to extrinsics

- chain-specs/paseo/polimec-paseo.spec.plain.json
- chain-specs/paseo/polimec-paseo.spec.raw.json
Change the `tokenSymbol` in the Paseo's chain-spec to avoid possible confusion.
> chore: change tokenSymbol in chain-spec

- pallets/funding/src/functions/7_ct_migration.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/tests/8_ct_migration.rs
Change the order, naming, and indexing of some extrinsics
Easier readability, and less guessing what the next index will be for new extrinsics
> 👨🏻‍💻 Reorg extrinsics

- justfile
- nodes/parachain/src/chain_spec/common.rs
- nodes/parachain/src/chain_spec/polimec_paseo.rs
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/7_ct_migration.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/5_remainder.rs
- pallets/funding/src/weights.rs
- polimec-common/common/src/lib.rs
- runtimes/polimec/src/weights/pallet_funding.rs
- runtimes/polimec/src/xcm_config.rs
- runtimes/shared-configuration/src/currency.rs
- Write new benchmarks for migration extrinsics
both running cargo test and dry-run-benchmarks just command
- I'm running the pallet benchmarks in AWS and will post the new weights in the next PR
> ✨ New CT Migration benchmarks

- pallets/funding/src/functions/misc.rs
- Add comment to Y variable calculation to avoid confusion.
- There was confusion that the Y variable could become higher than 1 when the funding amount reached was higher than the target funding (USD). This is not possible because `Perquintill` saturates to 1, but if we don't add a comment it might appear unintented.
- 2 identical comments on the Y calculations in `generate_evaluator_rewards_info` and `generate_liquidity_pools_and_long_term_holder_rewards`
> 📄 Small comment about Y variable

- pallets/funding/src/storage_migrations.rs
- pallets/linear-release/src/tests.rs
- runtimes/polimec/src/lib.rs
- scripts/chopsticks/polimec-testing/polkadot-polimec.yml
- Write storage migrations for new ProjectDetails
- Increase polimec runtime version
- Try runtime upgrade with chopsticks
```
try-runtime \
--runtime target/release/wbuild/polimec-runtime/polimec_runtime.compact.compressed.wasm \
on-runtime-upgrade \
live --uri wss://rpc.polimec.org:443
[2024-07-19T14:24:51Z INFO  remote-ext] replacing wss:// in uri with https://: "https://rpc.polimec.org:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-07-19T14:24:51Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0x8201ec98c57cb31e3d7b5fdf6ae7d295cc538d8e7a47849e12ee00ae5af64ca1
[2024-07-19T14:24:51Z INFO  remote-ext] since no prefix is filtered, the data for all pallets will be …
```
> ⬆️ Release 0.7.6

- pallets/funding/src/functions/misc.rs
- pallets/polimec-receiver/src/lib.rs
- Fix our pallet migration integration test
- We added a real benchmarked weight to the `confirm_pallet_migrations` extrinsic, but forgot to reflect that change when setting the max weight for the `ReportTransactStatus` message appended at the end of a migration.
The xcm logs showed that the message was overweight:
```
events::Polimec: RuntimeEvent::PolkadotXcm(Event::NotifyOverweight { query_id: 2, pallet_index: 80, call_index: 30, actual_weight: Weight { ref_time: 573050100, proof_size: 33831 }, max_budgeted_weight: Weight { ref_time: 700000000, proof_size: 10000 } })    
```
As you can see the actual weight was:
- `Weight { ref_time: 573050100, proof_size: 33831 }`
And the max weight we set was
- `Weight { ref_time: 700000000, proof_size: 10000 }`
Therefore we now increase the max …
> 🔧 Fix migration test

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/penpal/Cargo.toml
- integration-tests/src/tests/ct_migration.rs
- integration-tests/src/tests/e2e.rs
- integration-tests/src/tests/oracle.rs
- pallets/funding/Cargo.toml
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/instantiator/calculations.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/instantiator/mod.rs
- pallets/funding/src/instantiator/tests.rs
- pallets/funding/src/instantiator/types.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/runtime_api.rs
- pallets/funding/src/tests/1_application.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_community.rs
- pallets/funding/src/tests/5_remainder.rs
- pallets/funding/src/tests/6_funding_end.rs
- pallets/funding/src/tests/7_settlement.rs
- pallets/funding/src/tests/8_ct_migration.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/tests/mod.rs
- pallets/funding/src/tests/runtime_api.rs
- pallets/linear-release/src/tests.rs
- runtimes/polimec/src/lib.rs
- Add pallet-funding runtime APIs as requested in https://linear.app/polimec/issue/PLMC-582/runtime-api-to-have-less-logic-in-the-ui
- Add and modify instantiator functions to make the testing easier
Complex querying and calculations are done better in Rust with the full on-chain data and types than in Javascript on the front-end
- New file inside test folder "runtime_api.rs"
To get an overview of the main changes, check out runtime_api.rs on /src and on /tests folders, as well as the new tests.rs file on the instantiator, where I test the new functions.
The rest of the changed files should be more about reflecting the changes of the instantiator functions
> 😎 Runtime APIs

- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/2_evaluation.rs
- pallets/funding/src/lib.rs
- Root transition functions can now be called by anyone
- We no longer have automatic transitions
- Our transition logic already checks if a transition is supposed to happen or not, so no reason to gate it behind root
- This should be called automatically through an offchain script of OCW
- changed `ensure_root` to `ensure_signed` + some naming changes
In a later PR
> ✲ Transitions can be called by anyone

- pallets/funding/src/functions/misc.rs
- Remove the Y variable (percent usd reached from target) 
- Unnecessary complexity
- Evaluator rewards are always 30% of fee CTs, LTHB always 20% when evaluator rewards are given
Not yet
> 🚮 Remove "Y" variable from fee allocation

- pallets/funding/src/functions/1_application.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/functions/5_funding_end.rs
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/functions/7_ct_migration.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/types.rs
- runtimes/polimec/src/lib.rs
- There is now only one threshold configurable at runtime. Above the project is successful and evaluators rewarded, below project fails and evaluators slashed. No issuer decision
- Simplifies logic greatly
- Commented out all tests for now. Will be fixed in a later PR
> ✨ New evaluation reward/slash thresholds

- pallets/funding/src/functions/2_evaluation.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/functions/4_contribution.rs
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/instantiator/types.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/runtime_api.rs
- pallets/funding/src/types.rs
- Remove fields in `BidInfo` which were not needed
- Make retail multiplier limits a fixed range
- Less storage bloat
- Simplified logic, less storage overhead to keep track of past participations
- In the next PR
> 🗑️ Remove unnecessary bid fields

- pallets/funding/src/functions/2_evaluation.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/functions/5_funding_end.rs
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/functions/7_ct_migration.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/misc.rs
- We now emit project transition events
- We do it in the transition project function
- We now use the transition project function for every transition (before was used only till community round)
- We now use the same project status enum in the event as in the project details
- Events are emitted in the transition project function only
- Transition function is now always used when changing the project state in project_details
- `project_state_transition_event`
> ✌️ Fix project transition event

- pallets/funding/src/functions/2_evaluation.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/misc.rs
- runtimes/polimec/src/lib.rs
- runtimes/shared-configuration/src/funding.rs
- There's no more candle period, so AuctionOpening and AuctionClosing durations should be merged
- Naming of durations are now more consistent
- Removed both Auction periods and replaced them for one called `AuctionRoundDuration`
- Merged the durations in the shared-configuration
We moved from transitioning using the durations to the simple extrinsic `inst.go_to_next_state(project_id)` so no text fixes needed.
- Made all mock durations different to potentially catch some bugs. Had a problem before where I was assuming a closing duration was going on and it was the auctionInitializePeriod.
> 💥 Remove AuctionClosingDuration

- pallets/funding/src/functions/1_application.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/types.rs
- Remove the random en field from project details
- We forgor 💀
> 💥 Remove random end field

- pallets/funding/src/lib.rs
- Add a new extrinsic which calls the already included `do_mark_project_as_settled` extrinsic
- Any user should be able to transition the project from `SettlementStarted` to `SettlementFinished`. We need it for starting the migration
- Add an ensure_signed and a call to the do_ function
- new module for testing this extrinsic `mark_project_as_settled_extrinsic` in the next PR
> ✨ Add mark project settled extrinsic

- integration-tests/src/tests/ct_migration.rs
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/5_funding_end.rs
- pallets/funding/src/tests/6_settlement.rs
- pallets/funding/src/tests/7_ct_migration.rs
- pallets/funding/src/types.rs
- New tests for untested features
> ✅ New tests

- Cargo.lock
- integration-tests/penpal/Cargo.toml
- integration-tests/penpal/src/lib.rs
Penpal was not compiling correctly with the new sdk version
> 🔧 Fix penpal

- Cargo.lock
- integration-tests/penpal/Cargo.toml
- integration-tests/penpal/src/lib.rs
- pallets/funding/src/functions/4_contribution.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/tests/4_contribution.rs
- Participants could contribute with 0CTs, now we disallow it
- Useless storage consumption
- an ensure on the final ct bought
- New test
> 🙅🏻‍♂️ Disallow 0CT participation

- pallets/funding/src/storage_migrations.rs
- pallets/funding/src/tests/4_contribution.rs
- runtimes/polimec/src/custom_migrations/funding_holds.rs
- runtimes/polimec/src/custom_migrations/mod.rs
- runtimes/polimec/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
- scripts/chopsticks/genesis-polimec.yml
- Increase version of pallet_funding storage and polimec runtime
- Write storage migration for new holds without project id at runtime level, and ProjectDetails changes at pallet level
- New storage would be undecodable otherwise
We need to test it with chopsticks before merging. Try-runtime works
I compared the old vs new holds and the only change was the participation
I compared the old vs new ProjectDetails and the difference was the phaseTransitionPoints being replaced with `roundDuration: {
start: null
end: null
}`
and the status changed to `SettlementStarted: Failure` in the case of `FundingFailed`, and `SettlementStarted:Success` in the case of `SettlementStarted(FundingSuccessful)` 
Files are here: https://linear.app/polimec/issue/PLMC-601/manual-tests#comment-9b3008c7
> 🔖 Runtime Upgrade

- pallets/funding/Cargo.toml
- pallets/funding/src/lib.rs
- runtimes/polimec/Cargo.toml
When on-chain-release-build feature is used, don't compile the instantiator
Makes the runtime smaller
- Successfully ran pallet tests, integration tests, benchmark tests, dry-run-benches, and srtool wasm
> 🙅🏻‍♂️ Hide instantiator behind feature flag

- pallets/funding/Cargo.toml
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/6_settlement.rs
- runtimes/polimec/src/lib.rs
- Title
- Solving the schedule merging problem requires some functions not exposed through the trait, and we anyway don't care about making the funding pallet reusable. So easier to tightly couple our vesting pallet
- Remove duplicated config types
- Remove Vesting config type
- Add linear release Config to funding config required traits
> 👨🏻‍💻 Tightly couple linear-release to funding pallet

- pallets/linear-release/src/lib.rs
- Todo in linear release pallet was awaiting a hold reason check.
- We don't need it because if the 2 indexes declared don't exist for that hold reason then we will just get an error.
> Unneeded TODO removal

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/constants.rs
- integration-tests/src/tests/ct_migration.rs
- integration-tests/src/tests/e2e.rs
- integration-tests/src/tests/evaluator_slash_sideffects.rs
- integration-tests/src/tests/mod.rs
- pallets/funding/Cargo.toml
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/mock.rs
- pallets/on-slash-vesting/Cargo.toml
- pallets/on-slash-vesting/src/lib.rs
- pallets/on-slash-vesting/src/mock.rs
- pallets/on-slash-vesting/src/test.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/lib.rs
- Reduce vesting schedules of pallet-vesting after a slash is made when an evaluation is settled
- A user could have negative transferable balance if they had some tokens locked for vesting and then got slashed.
- Semi-generic solution which should be easily adapted to the Polkadot SDK. PR is [here](https://github.com/paritytech/polkadot-sdk/pull/5623).
- pallet-funding (in the future pallet-balances) accepts a tuple of items that implement a trait called on_slash.
- pallet funding calls this after slashing the evaluator (we don't use the slash interface so we call the trait directly. In the future this trait should also be called when using the slash function)
- We implement on pallet vesting the trait where we see how many tokens should be released at the moment of slashing, and then …
> ✨ Slashing behavior for pallet vesting

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/tests/credentials.rs
- pallets/funding/Cargo.toml
- pallets/funding/src/lib.rs
- pallets/on-slash-vesting/Cargo.toml
- pallets/on-slash-vesting/src/mock.rs
- pallets/on-slash-vesting/src/test.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/build.rs
- runtimes/polimec/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
- scripts/zombienet/polimec-paseo-local.toml
- Add support for the Ledger hardware wallet
- Add a new signed extension to the runtime, and conditional build of the wasm.
@lrazovic can you try it out with zombienet since you have a ledger nano?
There are 2 places where I had to initialise the signed extensions with ::new(), but not sure if the argument inside should be `true` or `false`. I set it to true
> 📒 Add Ledger support

- chain-specs/polkadot/polimec-raw-chain-spec.json
Add dwellir bootnode
To improve network distribution and reslience
Via Infra
```
./polimec-node --chain=polimec --reserved-nodes=/dns/polimec-boot-ng.dwellir.com/tcp/443/wss/p2p/12D3KooWDWbXpHidJLEqpUwyttAfkFubUxDN4APsFi9gUutxSoqm
```
```
./polimec-node --chain=polimec --reserved-nodes=/dns/polimec-boot-ng.dwellir.com/tcp/30370/p2p/12D3KooWDWbXpHidJLEqpUwyttAfkFubUxDN4APsFi9gUutxSoqm
```
> add dwellir bootnode to polimec

- chain-specs/polkadot/polimec-raw-chain-spec.json
Please add RadiumBlock bootnodes to Polimec chain spec
Better p2p connectivity
./polimec-node --chain=polimec --reserved-only --reserved-nodes=/dns/polimec-bootnode.radiumblock.com/tcp/30333/p2p/12D3KooWEKBtb1JcCewtTtCJKQq5EXTs3qe4mNLMHGG71kGAaK63
./polimec-node --chain=polimec --reserved-only --reserved-nodes=/dns/polimec-bootnode.radiumblock.com/tcp/30336/wss/p2p/12D3KooWEKBtb1JcCewtTtCJKQq5EXTs3qe4mNLMHGG71kGAaK63
> Add RadiumBlock bootnodes to Polimec

- Cargo.lock
- bacon.toml
- integration-tests/Cargo.toml
- integration-tests/src/constants.rs
- integration-tests/src/tests/credentials.rs
- integration-tests/src/tests/e2e.rs
- pallets/proxy-bonding/src/functions.rs
- pallets/proxy-bonding/src/lib.rs
- runtimes/polimec/src/lib.rs
- runtimes/shared-configuration/src/fee.rs
Add new e2e tests
OTM Flow and simplifications were added, so we needed to recheck all the numbers.
Delete everything and start over with this spreadsheet:
https://docs.google.com/spreadsheets/d/1BiKZCf50S9U_jiPPShTqmL6A_DUlFqwx/edit?gid=114355434#gid=114355434
Only one test in the e2e.rs file that goes over everything.
I added a bacon.toml config file. [bacon](https://dystroy.org/bacon/) is the [successor](https://www.reddit.com/r/rust/comments/1ftc7cj/cargo_watch_is_on_life_support/) to cargo watch. Its a program you leave running in the background and dynamically shows you errors from the compiler instead of having to constantly call cargo check or cargo test.
Kind of what rust-analyzer does, but I usually have it disabled because it makes everything mega slow.
> ✅ New e2e tests

- Cargo.lock
- integration-tests/src/tests/transaction_payment.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/custom_migrations/funding_holds.rs
- runtimes/polimec/src/lib.rs
- runtimes/shared-configuration/Cargo.toml
- runtimes/shared-configuration/src/fee.rs
- Make our Asset fee-paying Signed Extension compatible with `@polkadot/api` JS packages.
- The  `@polkadot/api` JS packages work better if the `assetId` is a `MultiLocation`/`Location`, so our initial `u32` based solution didn't work
- Make the signed extension accept a `xcm::v3::MultiLocation`, and convert it internally to a `u32`.
> 💥 Switch to MultiLocation in the SignedExtension

- integration-tests/src/tests/evaluator_slash_sideffects.rs
- integration-tests/src/tests/otm_edge_cases.rs
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/instantiator/calculations.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/instantiator/traits.rs
- pallets/funding/src/instantiator/types.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_contribution.rs
- pallets/funding/src/tests/6_settlement.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/tests/mod.rs
- pallets/funding/src/tests/runtime_api.rs
- Fix all tests
- They were failing due to a USDT ED now being required
- Create new inst functions to mint the ed and call them in all tests.
> ✅ Fix funding asset ED tests

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/tests/credentials.rs
- integration-tests/src/tests/transaction_payment.rs
- pallets/dispenser/src/extensions.rs
- pallets/dispenser/src/lib.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/benchmark_helpers.rs
- runtimes/polimec/src/lib.rs
We forked parity's skip-feeless-payment pallet because it was buggy and unmerged. It's now stable so we can use it
So it's maintained as part of the SDK and not by us
The signed extension needs also to be included as a pallet on the runtime.
The actual extension looks almost identical to ours
Test the existing tests in integration_tests::credeintals
Q: are we actually testing that you cannot dispense twice using our custom CheckNonce extension?
> ♲ Swap our custom to parity's skip-feeless-payment pallet

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/tests/mod.rs
- integration-tests/src/tests/runtime_apis.rs
- polimec-common/common/Cargo.toml
- polimec-common/common/src/lib.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
- scripts/zombienet/polimec-paseo-local.toml
Add XCM payment apis to the runtime
Most are just a simple copy paste to the pallet function, but a couple of them need some specific config due to asset payment.
integration tests in `runtime_apis.rs`
> 📡 Add XCM Runtime APIs

- pallets/funding/src/mock.rs
- pallets/funding/src/runtime_api.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_contribution.rs
- pallets/funding/src/tests/runtime_api.rs
- runtimes/polimec/src/lib.rs
New API to get the CTs and OTM fee (in the funding asset) by inputting the project id, funding asset, and funding asset amount
Needed for the UI
> 👾 New Funding Runtime API

- integration-tests/src/tests/otm_edge_cases.rs
- pallets/funding/src/functions/2_evaluation.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/functions/4_contribution.rs
- pallets/funding/src/runtime_api.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_contribution.rs
- pallets/funding/src/tests/runtime_api.rs
Disallow participations done after the round end, and before the project was transitioned to a new state
This was unintended behavior
One more ensure in each function. Quite simple
One new failure test for evaluate/bid/contribute
> 🙅🏻‍♂️ Add end block check on participations

- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/tests/defaults.rs
- integration-tests/src/tests/ethereum_support.rs
- integration-tests/src/tests/evaluator_slash_sideffects.rs
- pallets/funding/Cargo.toml
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/instantiator/calculations.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/instantiator/traits.rs
- pallets/funding/src/instantiator/types.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_contribution.rs
- pallets/funding/src/tests/6_settlement.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/tests/mod.rs
- pallets/funding/src/tests/runtime_api.rs
- pallets/funding/src/types.rs
- pallets/polimec-receiver/src/lib.rs
- polimec-common/common/src/lib.rs
- runtimes/polimec/Cargo.toml
- Add tests
- Test each new extrinsic
- Test an ethereum project can be successfully funded
- Test that the migration info is correctly setup with either the ETH or DOT account
> ✅ ETH Compatibility Tests

- pallets/funding/src/functions/2_evaluation.rs
- All rounds that don't have an end depending on time, should have a None end. This includes `FundingSuccessful`, `FundingFailed`, all Settlement states, and all Migration states.
- No new tests needed since its something affecting the UI
> 🔧 Set round end block to None on evaluation fail

- Cargo.lock
- integration-tests/src/constants.rs
- integration-tests/src/tests/ethereum_support.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/4_contribution.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/types.rs
- pallets/oracle-ocw/src/mock.rs
- pallets/oracle-ocw/src/types.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
- runtimes/shared-configuration/src/currency.rs
Add WETH from AssetHub as an `AcceptedFundingAsset`
- Add new enum variant
- Add asset multilocation to xcm filter
- `wap_from_different_funding_assets` modified to add WETH
We are missing the following PRs before we can release this feature:
- Integration test with chopsticks
- Price fetcher with the oracle
> WETH from AssetHub support

- Cargo.lock
- pallets/funding/src/mock.rs
- pallets/funding/src/runtime_api.rs
- pallets/funding/src/storage_migrations.rs
- pallets/proxy-bonding/src/mock.rs
- runtimes/polimec/Cargo.toml
- runtimes/polimec/src/custom_migrations/asset_id_migration.rs
- runtimes/polimec/src/custom_migrations/mod.rs
- runtimes/polimec/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
Migrate all storage that mentioned u32 asset id to a Location
Previous PR changed this
Its technically a new storage item since the asset id was used as a key, so we delete the old storage and create a new one for each item.
we did a manual override with chopsticks and a try-runtime run and it worked.
> AssetId Storage Migration

- pallets/funding/src/functions/1_application.rs
- pallets/funding/src/functions/2_evaluation.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/functions/4_contribution.rs
- pallets/funding/src/functions/7_ct_migration.rs
Refund the extrinsic execution fee for calls that require a JWT
The fee payment is used to avoid spamming and stalling the chain, but all JWT calls from regular KYCs need to either pay a fee with OTM, or lock up PLMC.
And the other ones are locked behind an institutional JWT, so even if they act malicious we could check who they are and take action.
This should provide better UX, since you can say you spend 100USDT and spend 100USDT, instead of 100.03
Instead of returning `Ok(())` return 
```
Ok(PostDispatchInfo{
actual_weight: None,
pays_fee: Pays::No,
})
```
Tests don't include fee payments for extrinsics. So only way I can see to test this is creating a network with chopsticks/zombienet and trying it out ourselves.
For now it hasn't been tested, but its a simple change so should work.
> 🎗️ Feeless calls

- integration-tests/src/tests/e2e.rs
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/functions/1_application.rs
- pallets/funding/src/functions/5_funding_end.rs
- pallets/funding/src/functions/6_settlement.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/instantiator/calculations.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/instantiator/tests.rs
- pallets/funding/src/lib.rs
- pallets/funding/src/runtime_api.rs
- pallets/funding/src/tests/2_evaluation.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/6_settlement.rs
- pallets/funding/src/tests/misc.rs
- pallets/funding/src/tests/runtime_api.rs
- pallets/funding/src/types.rs
- Remove the WAP
- Accepted bids don't get any refund since there's no difference between price paid and final price.
- Only Partially accepted bids get some refund
- Rejected bids still get full refund
- No contribution round to profit from the WAP, so only thing we're doing is making the system more confusing and giving less funds to the issuer.
- Remove all references to the WAP
- Don't give refunds based on the price difference
- Delete WAP related tests
- Amend the other tests
> 🚮 Remove WAP

- integration-tests/chopsticks/overrides/polimec.ts
- integration-tests/chopsticks/overrides/polkadot-hub.ts
- integration-tests/chopsticks/src/constants.ts
- integration-tests/chopsticks/src/managers/BridgeHubManager.ts
- integration-tests/chopsticks/src/managers/PolimecManager.ts
- integration-tests/chopsticks/src/managers/PolkadotHubManager.ts
- integration-tests/chopsticks/src/managers/PolkadotManager.ts
- integration-tests/chopsticks/src/tests/bridge.test.ts
- integration-tests/chopsticks/src/transfers/BridgeToPolimec.ts
- integration-tests/chopsticks/src/transfers/PolimecToHub.ts
- integration-tests/chopsticks/src/types.ts
- integration-tests/src/constants.rs
- integration-tests/src/tests/defaults.rs
- integration-tests/src/tests/evaluator_slash_sideffects.rs
- integration-tests/src/tests/oracle.rs
- integration-tests/src/tests/runtime_apis.rs
- nodes/parachain/src/chain_spec/common.rs
- pallets/funding/src/benchmarking.rs
- pallets/funding/src/instantiator/calculations.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/mock.rs
- pallets/funding/src/tests/1_application.rs
- pallets/funding/src/tests/3_auction.rs
- pallets/funding/src/tests/mod.rs
- pallets/funding/src/tests/runtime_api.rs
- pallets/funding/src/types.rs
- polimec-common/common/src/assets.rs
- runtimes/polimec/src/benchmark_helpers.rs
- runtimes/polimec/src/xcm_config.rs
- runtimes/shared-configuration/src/currency.rs
This PR includes a series of changes to update the asset references from WETH to ETH across multiple files in the integration tests. The changes ensure consistency in naming and update the relevant asset locations, constants, and test cases.
Key changes include:
* Updated the `weth_location` to `eth_location` and modified its structure in `integration-tests/chopsticks/overrides/polimec.ts`.
* Replaced `weth_location` with `eth_location` in the `polimec_storage` export in `integration-tests/chopsticks/overrides/polimec.ts`.
* Updated the `Metadata` entry to use `eth_location` instead of `weth_location` in `integration-tests/chopsticks/overrides/polimec.ts`.
* Changed `WETH_AMOUNT` to `ETH_AMOUNT` in `integration-tests/chopsticks/src/constants.ts`.
* Updated the `Asset` enum to replace …
> ♻️ Replace WETH with Ethereum-native ETH

- integration-tests/chopsticks/README.md
- integration-tests/chopsticks/bun.lock
- integration-tests/chopsticks/overrides/polimec.ts
- integration-tests/chopsticks/package.json
- integration-tests/chopsticks/src/managers/PolimecManager.ts
- integration-tests/chopsticks/src/setup.ts
- integration-tests/chopsticks/src/tests/polimec.test.ts
- integration-tests/chopsticks/src/transfers/BaseTransfer.ts
- integration-tests/chopsticks/src/transfers/BridgeToPolimec.ts
- integration-tests/chopsticks/src/transfers/HubToPolimec.ts
- integration-tests/chopsticks/src/transfers/PolimecToHub.ts
- integration-tests/chopsticks/src/transfers/PolkadotToPolimec.ts
- integration-tests/chopsticks/src/types.ts
This pull request includes several updates and improvements to the `integration-tests/chopsticks` project. The main changes involve updating dependencies, enhancing test cases, and cleaning up the codebase by removing unnecessary console logs and imports.
* Updated `@acala-network/chopsticks` to version `1.0.3` and `@polkadot-labs/hdkd` to version `0.0.12` in `package.json`.
* Updated `polkadot-api` dependency to version `^1.9.3` in `package.json`.
* Re-enabled previously commented-out test cases for transferring USDC, USDT, and DOT to the Hub in `polimec.test.ts`.
* Removed unnecessary console logs from various files, including `PolimecManager.ts`, `BaseTransfer.ts`, `BridgeToPolimec.ts`, `HubToPolimec.ts`, `PolimecToHub.ts`, and `PolkadotToPolimec.ts`. …
> 🐛 Update the integration tests

- Cargo.lock
- Cargo.toml
- README.md
- integration-tests/Cargo.toml
- nodes/parachain/Cargo.toml
- pallets/proxy-bonding/Cargo.toml
- polimec-common/common/src/assets.rs
- polimec-common/common/src/credentials/mod.rs
- polimec-common/common/src/lib.rs
- runtimes/polimec/Cargo.toml
- runtimes/shared-configuration/src/funding.rs
This PR includes some small updates and improvements across multiple files, focusing on version bump, dependency management, and code refactoring. The most important changes include updating the project version, refining the README, and reorganizing dependencies in several `Cargo.toml` files.
Version and Documentation Updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L34-R34): Updated the project version from `0.9.0` to `1.0.0`.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-L4): Removed the warning about heavy development and updated various sections to reflect the latest changes and improvements. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed510687 …
> 🔖 Release Polimec 1.0.0

- pallets/funding/src/lib.rs
- pallets/funding/src/migrations/mod.rs
- pallets/funding/src/migrations/storage_migrations.rs
- pallets/funding/src/migrations/vesting_info.rs
- runtimes/polimec/src/lib.rs
migrates UserMigrations to use relay chain block number, assuming change from 12s block time to 6s. Tested with try-runtime and a unit test
> 🏗️ Funding pallet migration for enabling async backing

- Cargo.lock
- pallets/funding/src/migrations/vesting_info.rs
- pallets/funding/src/tests/mod.rs
- pallets/linear-release/Cargo.toml
- pallets/linear-release/src/lib.rs
- pallets/linear-release/src/migrations.rs
- pallets/linear-release/src/mock.rs
- runtimes/polimec/src/custom_migrations/linear_release.rs
- runtimes/polimec/src/custom_migrations/mod.rs
- runtimes/polimec/src/lib.rs
This pull request introduces a significant update to the `linear-release` pallet, including a migration to version 1 of the vesting storage format, as well as various related code adjustments across multiple files. The changes are primarily focused on adding migration support, updating dependencies, and cleaning up unused imports.
* Introduced a new migration module in `linear-release` (`pallets/linear-release/src/migrations.rs`) to handle the transition of vesting schedules to version 1. This includes logic to adjust starting blocks and per-block release rates based on relay chain block numbers.
* Added the `STORAGE_VERSION` constant and `#[pallet::storage_version]` attribute to the `linear-release` pallet to track the current storage version. …
> 🏗️ Linear release block number provider migration

- integration-tests/src/constants.rs
- nodes/parachain/src/chain_spec/common.rs
- pallets/parachain-staking/src/inflation.rs
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/mock.rs
- runtimes/polimec/src/lib.rs
- runtimes/shared-configuration/src/time.rs
This pull request introduces a refactor to centralize the definition of `BLOCKS_PER_YEAR` across the codebase, replacing hardcoded values with a configurable constant. This improves maintainability and consistency. Key changes include modifications to the `pallet_parachain_staking` module, runtime configurations, and shared time constants.
* **`pallet_parachain_staking` updates:**
- Added `BLOCKS_PER_YEAR` as an associated constant in the `Config` trait, making it configurable per runtime. (`pallets/parachain-staking/src/lib.rs`, [pallets/parachain-staking/src/lib.rsR203-R205](diffhunk://#diff-842251b834245800808bd740184c1e3b18c6af1f95fb1bd4d484420017fdf86eR203-R205))
- Updated the `reset_round` method to use the configurable `BLOCKS_PER_YEAR` instead of a hardcoded value. …
> 🏗️ Migrate pallet staking to use new block time

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/constants.rs
- integration-tests/src/lib.rs
- integration-tests/src/tests/mod.rs
- integration-tests/src/tests/transact.rs
This pull request introduces several changes to the integration tests and runtime configurations, primarily focused on replacing `rococo-runtime` with `westend-runtime` and adding support for the `AssetHubWestend` parachain. The changes include updates to dependencies, constants, runtime configurations, and the addition of new test cases for cross-chain transactions.
* Updated dependencies in `Cargo.toml` files to replace `rococo-runtime` and `rococo-runtime-constants` with `westend-runtime` and `westend-runtime-constants` (`Cargo.toml`, `integration-tests/Cargo.toml`). [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L250-R255) [[2]](diffhunk://#diff-ca620c1799a0fbfe846664793344b0d95a4f906636d2fbf307bff69f6ec81849L65-R65) …
> ✅ Add XCM Transact emulator tests

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/tests/evaluator_slash_sideffects.rs
- integration-tests/src/tests/transact.rs
- pallets/funding/Cargo.toml
- pallets/funding/src/functions/3_auction.rs
- pallets/on-slash-vesting/Cargo.toml
- runtimes/polimec/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
This pull request includes updates to the versioning of the Polimec project, reflecting improvements or changes in the runtime and overall project release. The most important changes are:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L34-R34): Updated the project version from `1.0.0` to `1.1.0`, indicating a new release with potentially significant updates or improvements.
* [`runtimes/polimec/src/lib.rs`](diffhunk://#diff-fa44a5ad015c5d189a690374b9164d3a58b7218228b56c151327dd62d143ee1bL245-R248): Incremented the `spec_version` from `1_000_000` to `1_001_000` and the `transaction_version` from `7` to `8` in the `RuntimeVersion` definition, signaling updates to the runtime specifications and transaction logic.
> 🔖 Release Polimec 1.1.0

- Cargo.lock
- Cargo.toml
- runtimes/polimec/src/lib.rs
This PR updates dependencies in `Cargo.toml` and makes runtime changes in `runtimes/polimec/src/lib.rs`. The updates primarily include version bumps for various Polkadot-SDK dependencies.
* Updated versions for Substrate-related crates, including `xcm-emulator`, `frame-benchmarking`, `frame-executive`, `sp-npos-elections`, `pallet-scheduler`, `pallet-xcm`, and `sp-api-proc-macro`.
* Updated runtime versions for `westend-runtime`, `asset-hub-westend-runtime`, and `emulated-integration-tests-common`.
* Simplified the `migrations` module by removing already executed migration, such as `RemovePallet`, and other legacy migration logic. 
* Incremented the `spec_version` from `1_001_000` to `1_001_001` and the `transaction_version` from `8` to `9`.
> 🚑️ Bump frame-executive and sp-api-proc-macro

- pallets/funding/src/instantiator/macros.rs
This pull request introduces significant improvements and new features to macros in the `pallets/funding/src/instantiator/macros.rs` file. The changes include enhancements to the `assert_close_enough!` macro, the addition of a new `is_close_enough!` macro, and a comprehensive overhaul of the `find_event!` macro to support more advanced use cases. These updates improve functionality, readability, and flexibility when working with runtime events and assertions in the Substrate framework.
* Improved logic to handle edge cases where both values are zero, ensuring `Perquintill::one()` is returned in such scenarios.
* Enhanced support for custom error messages by restructuring the macro to accept variadic arguments for the message.
* Refactored the implementation for better readability and …
> 🎨 Macros update and documentation

- Cargo.toml
- pallets/dispenser/src/extensions.rs
- pallets/funding/src/functions/1_application.rs
- pallets/funding/src/functions/3_auction.rs
- pallets/funding/src/functions/5_settlement.rs
- pallets/funding/src/functions/misc.rs
- pallets/funding/src/instantiator/calculations.rs
- pallets/funding/src/instantiator/chain_interactions.rs
- pallets/funding/src/instantiator/mod.rs
- pallets/funding/src/instantiator/types.rs
- pallets/funding/src/types.rs
- pallets/linear-release/src/lib.rs
- pallets/on-slash-vesting/src/lib.rs
- pallets/proxy-bonding/src/functions.rs
- polimec-common/common/src/lib.rs
- runtimes/polimec/src/xcm_config.rs
This pull request introduces several updates across multiple files to improve code consistency, enhance performance, and adopt best practices. Key changes include enforcing stricter linting rules, replacing redundant `.clone()` calls with direct references, adding `const` constructors for better compile-time optimizations, and removing unnecessary imports. These changes aim to streamline the codebase and improve maintainability.
* Updated `Cargo.toml` to enforce stricter linting by changing `redundant_clone` from "warn" to "deny" and adding a new lint rule `missing-const-for-fn` set to "warn".
* Replaced `.clone()` calls with direct references or moved values where cloning was unnecessary, e.g., in `pallets/funding/src/functions/1_application.rs`, …
> ⚡️ Remove useless clone
